 # ---------------------------------------------------------------------------- #
 #                      Config for PointerCAD Model Training                      #
 # ---------------------------------------------------------------------------- #
 
 
 
 # ---------------------- Configuration for Model ---------------------- #
model:
  base_model: "Qwen/Qwen2.5-7B-Instruct"


# --------------- Configuration related to training dataloader --------------- #
dataset:
  # Root directory of the dataset
  dataset_dir: "/mnt/afs_01e/mayi-folder/ParamCAD/dataset/paramcad-addon"
  # JSON file containing information about train, test, and validation splits
  split_filepath: "/mnt/afs_01e/mayi-folder/ParamCAD/dataset/paramcad-addon/train_val_test.json"
  # Maximum sequence length for input data
  max_seq_len: 512


# ------------------------- Test configuration ------------------------- #
test:
  num_workers: 1
  batch_size: 1
  prefetch_factor: 1
  checkpoint_path: "/mnt/afs_01e/mayi-folder/ParamCAD/cad/ParamCAD/plan-param-tie-mask/log/2026-02-11/11:19/model.pth"
  log_dir: "./log"
  save_stl: True
  save_step: True


# --------------- Additional information (leave empty for now) --------------- #
info: "test"
